#!/usr/bin/env python
"""Render every authored curriculum surface from the single-source manifest.

The curriculum's *shape* — the module list, the track list, the ordering /
numbering, and the counts — lives in exactly one place: the modules' front
matter plus :data:`xrpl_lab.curriculum.TRACKS`, surfaced by
:func:`xrpl_lab.curriculum_manifest.build_manifest`. Every other place that
states that shape (the README module table, the Starlight handbook tables, the
getting-started / index counts, and the marketing site-config rows) used to
hand-encode it and drifted.

This generator regenerates the *structured* blocks of those surfaces in place,
between clearly-fenced ``BEGIN curriculum:auto`` / ``END curriculum:auto``
markers. Editorial prose OUTSIDE the fences (logos, badges, taglines, the
handbook narrative, the README's richer "what you learn / what you prove"
columns if a human adds them) is preserved untouched.

Idempotent: running it twice yields no diff. ``tests/test_docs_drift.py``
re-renders these blocks and fails CI if any surface drifts from the manifest.

Usage::

    python scripts/gen_docs.py            # rewrite all surfaces in place
    python scripts/gen_docs.py --check    # exit 1 if any surface is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Allow running as a bare script (python scripts/gen_docs.py) without an install.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from xrpl_lab.curriculum_manifest import (  # noqa: E402
    CurriculumManifest,
    build_manifest,
)

# ── Paths ────────────────────────────────────────────────────────────
README = _REPO_ROOT / "README.md"
HANDBOOK_MODULES = _REPO_ROOT / "site/src/content/docs/handbook/modules.md"
HANDBOOK_INDEX = _REPO_ROOT / "site/src/content/docs/handbook/index.md"
HANDBOOK_GETTING_STARTED = _REPO_ROOT / "site/src/content/docs/handbook/getting-started.md"
CURRICULUM_JSON = _REPO_ROOT / "site/src/data/curriculum.json"

# ── Fence markers ────────────────────────────────────────────────────
# Each authored block carries a uniquely-named region so multiple generated
# blocks can live in one file. The DO-NOT-EDIT note rides inside every block.
_NOTE = "generated by scripts/gen_docs.py — do not hand-edit; run the generator"


def _md_begin(region: str) -> str:
    return f"<!-- BEGIN curriculum:auto {region} -->"


def _md_end(region: str) -> str:
    return f"<!-- END curriculum:auto {region} -->"


def _md_note() -> str:
    return f"<!-- {_NOTE} -->"


# ── Generic in-place fence replacement (idempotent) ──────────────────


def replace_block(text: str, begin: str, end: str, body: str) -> str:
    """Replace the content between *begin* and *end* markers with *body*.

    The markers themselves are preserved. *body* is placed on its own lines
    between them. Raises if the markers are absent or malformed so a renamed
    surface fails loudly instead of silently not updating.
    """
    bi = text.find(begin)
    ei = text.find(end)
    if bi == -1 or ei == -1 or ei < bi:
        raise ValueError(f"Markers not found / malformed: {begin!r} .. {end!r}")
    head = text[: bi + len(begin)]
    tail = text[ei:]
    return f"{head}\n{body}\n{tail}"


# ── Counts phrasing (one consistent string everywhere) ───────────────


def counts_sentence(manifest: CurriculumManifest) -> str:
    """Canonical counts phrasing reused across surfaces.

    The capstone is one of the tracks, so "across ten tracks" is honest and is
    the clearest single phrasing — we use it consistently everywhere.
    """
    n_modules = manifest.totals["modules"]
    n_tracks = manifest.totals["tracks"]
    return f"{n_modules} modules across {_num_word(n_tracks)} tracks"


_NUM_WORDS = {
    1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
    6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
    11: "eleven", 12: "twelve",
}


def _num_word(n: int) -> str:
    return _NUM_WORDS.get(n, str(n))


def track_names_phrase(manifest: CurriculumManifest) -> str:
    """Comma-joined track display labels, Oxford-and on the last."""
    labels = [tc.label for tc in manifest.track_counts]
    if len(labels) <= 1:
        return labels[0] if labels else ""
    return ", ".join(labels[:-1]) + ", and " + labels[-1]


def _prereq_cell(manifest: CurriculumManifest, requires: list[str]) -> str:
    """Render a Prerequisites cell as human titles (id → title), or em dash."""
    if not requires:
        return "—"
    titles = []
    for rid in requires:
        m = manifest.module_by_id(rid)
        titles.append(m.title if m else rid)
    return ", ".join(titles)


# ── README ───────────────────────────────────────────────────────────


def render_readme_intro(manifest: CurriculumManifest) -> str:
    """README intro line under the Modules heading (counts + track names)."""
    return (
        f"{counts_sentence(manifest).capitalize()}: "
        f"{track_names_phrase(manifest)}.\n"
        "Prerequisites are explicit — the CLI and linter enforce them.\n\n"
        "The `#` column matches the order shown by `xrpl-lab list` "
        "(canonical track order)."
    )


def render_readme_table(manifest: CurriculumManifest) -> str:
    """README module table — structured columns only (no editorial prose)."""
    lines = [
        "| # | Module | Track | Mode | Prerequisites | Produces |",
        "|---|--------|-------|------|---------------|----------|",
    ]
    for m in manifest.modules:
        lines.append(
            f"| {m.index} | {m.title} | {m.track} | {m.mode} | "
            f"{_prereq_cell(manifest, m.requires)} | {', '.join(m.produces)} |"
        )
    return "\n".join(lines)


def render_readme_tracks(manifest: CurriculumManifest) -> str:
    """README Tracks legend (one bullet per track, in canonical order)."""
    from xrpl_lab.curriculum_manifest import TRACK_FOCUS

    lines = []
    for tc in manifest.track_counts:
        focus = TRACK_FOCUS.get(tc.track, "")
        lines.append(f"- **{tc.track}** — {focus}")
    return "\n".join(lines)


def update_readme(manifest: CurriculumManifest, text: str) -> str:
    text = replace_block(
        text,
        _md_begin("readme-intro"),
        _md_end("readme-intro"),
        f"{_md_note()}\n{render_readme_intro(manifest)}",
    )
    text = replace_block(
        text,
        _md_begin("readme-table"),
        _md_end("readme-table"),
        f"{_md_note()}\n{render_readme_table(manifest)}",
    )
    text = replace_block(
        text,
        _md_begin("readme-tracks"),
        _md_end("readme-tracks"),
        f"{_md_note()}\n{render_readme_tracks(manifest)}",
    )
    return text


# ── Handbook: modules.md ──────────────────────────────────────────────


def render_handbook_intro(manifest: CurriculumManifest) -> str:
    return (
        f"XRPL Lab includes {counts_sentence(manifest)}. Each module teaches "
        "one skill and produces a verifiable artifact. Prerequisites are "
        "explicit and enforced."
    )


def render_handbook_tracks_table(manifest: CurriculumManifest) -> str:
    """Per-track overview table: Track | Focus | Modules | Mode."""
    from xrpl_lab.curriculum_manifest import TRACK_FOCUS

    # Mode per track: if every module in the track shares a mode, show it;
    # otherwise "mixed". Derived, never hand-set.
    modes_by_track: dict[str, set[str]] = {}
    for m in manifest.modules:
        modes_by_track.setdefault(m.track, set()).add(m.mode)

    lines = [
        "| Track | Focus | Modules | Mode |",
        "|-------|-------|---------|------|",
    ]
    for tc in manifest.track_counts:
        modes = modes_by_track.get(tc.track, set())
        mode = next(iter(modes)) if len(modes) == 1 else "mixed"
        focus = TRACK_FOCUS.get(tc.track, "")
        lines.append(f"| **{tc.track}** | {focus} | {tc.count} | {mode} |")
    return "\n".join(lines)


def render_handbook_per_track(manifest: CurriculumManifest) -> str:
    """Per-track numbered module tables (the bulk of modules.md)."""
    blocks: list[str] = []
    # Group modules by track, preserving canonical order.
    by_track: dict[str, list] = {}
    for m in manifest.modules:
        by_track.setdefault(m.track, []).append(m)

    for tc in manifest.track_counts:
        mods = by_track.get(tc.track, [])
        if not mods:
            continue
        # Heading: AMM is dry-run only — annotate it from derived mode, not by hand.
        modes = {m.mode for m in mods}
        suffix = " (dry-run only)" if modes == {"dry-run"} else ""
        blocks.append(f"## {tc.label}{suffix}\n")
        blocks.append("| # | Module | Prerequisites | Produces |")
        blocks.append("|---|--------|---------------|----------|")
        for m in mods:
            blocks.append(
                f"| {m.index} | {m.title} | "
                f"{_prereq_cell(manifest, m.requires)} | {', '.join(m.produces)} |"
            )
        blocks.append("")  # trailing blank line between tracks
    return "\n".join(blocks).rstrip()


def update_handbook_modules(manifest: CurriculumManifest, text: str) -> str:
    text = replace_block(
        text,
        _md_begin("handbook-intro"),
        _md_end("handbook-intro"),
        f"{_md_note()}\n{render_handbook_intro(manifest)}",
    )
    text = replace_block(
        text,
        _md_begin("handbook-tracks-table"),
        _md_end("handbook-tracks-table"),
        f"{_md_note()}\n{render_handbook_tracks_table(manifest)}",
    )
    text = replace_block(
        text,
        _md_begin("handbook-per-track"),
        _md_end("handbook-per-track"),
        f"{_md_note()}\n{render_handbook_per_track(manifest)}",
    )
    return text


# ── Handbook: index.md ────────────────────────────────────────────────


def render_index_count(manifest: CurriculumManifest) -> str:
    """The modules-row cell in index.md's 'What's in the handbook' table."""
    return (
        f"All {counts_sentence(manifest)} — {track_names_phrase(manifest)}"
    )


def update_handbook_index(manifest: CurriculumManifest, text: str) -> str:
    return replace_block(
        text,
        _md_begin("index-count"),
        _md_end("index-count"),
        f"{_md_note()}\n{render_index_count(manifest)}",
    )


# ── Handbook: getting-started.md ──────────────────────────────────────


def render_getting_started_tracks(manifest: CurriculumManifest) -> str:
    """Counts intro + track legend in getting-started.md."""
    from xrpl_lab.curriculum_manifest import TRACK_FOCUS

    lines = [
        f"Modules are organized into {_num_word(manifest.totals['tracks'])} "
        "tracks with explicit prerequisites (the order below matches "
        "`xrpl-lab list`):",
        "",
    ]
    for tc in manifest.track_counts:
        focus = TRACK_FOCUS.get(tc.track, "")
        lines.append(f"- **{tc.track}** — {focus}")
    return "\n".join(lines)


def update_getting_started(manifest: CurriculumManifest, text: str) -> str:
    return replace_block(
        text,
        _md_begin("getting-started-tracks"),
        _md_end("getting-started-tracks"),
        f"{_md_note()}\n{render_getting_started_tracks(manifest)}",
    )


# ── Site: curriculum.json (imported by site-config.ts) ────────────────


def render_curriculum_json(manifest: CurriculumManifest) -> str:
    """Generated data the marketing site-config imports.

    Keeps the SiteConfig TS type valid: ``rows`` is ``string[][]`` exactly as
    ``DataTableSectionDef.rows`` expects. ``subtitle`` is the counts string;
    ``moduleCount`` feeds the hero + features copy so no number is hand-typed.
    """
    rows = [[m.title, m.track, ", ".join(m.produces)] for m in manifest.modules]
    payload = {
        "_generated": _NOTE,
        "moduleCount": manifest.totals["modules"],
        "trackCount": manifest.totals["tracks"],
        "countsSentence": counts_sentence(manifest),
        "columns": ["Module", "Track", "Produces"],
        "rows": rows,
    }
    return json.dumps(payload, indent=2) + "\n"


# ── Orchestration ─────────────────────────────────────────────────────


def render_all(manifest: CurriculumManifest) -> dict[Path, str]:
    """Return {path: new_full_text} for every surface, without writing."""
    out: dict[Path, str] = {}
    out[README] = update_readme(manifest, README.read_text(encoding="utf-8"))
    out[HANDBOOK_MODULES] = update_handbook_modules(
        manifest, HANDBOOK_MODULES.read_text(encoding="utf-8")
    )
    out[HANDBOOK_INDEX] = update_handbook_index(
        manifest, HANDBOOK_INDEX.read_text(encoding="utf-8")
    )
    out[HANDBOOK_GETTING_STARTED] = update_getting_started(
        manifest, HANDBOOK_GETTING_STARTED.read_text(encoding="utf-8")
    )
    out[CURRICULUM_JSON] = render_curriculum_json(manifest)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Exit 1 if any surface would change (CI drift gate), write nothing.",
    )
    args = parser.parse_args()

    manifest = build_manifest()
    rendered = render_all(manifest)

    stale: list[Path] = []
    for path, new_text in rendered.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != new_text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(new_text, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale (run scripts/gen_docs.py to regenerate):")
            for p in stale:
                print(f"  {p.relative_to(_REPO_ROOT)}")
            return 1
        print("All curriculum surfaces are up to date.")
        return 0

    if stale:
        print(f"Regenerated {len(stale)} surface(s):")
        for p in stale:
            print(f"  {p.relative_to(_REPO_ROOT)}")
    else:
        print("No changes — all surfaces already match the manifest.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
